name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask requests python-dotenv

    - name: Run tests
      run: |
        # Add commands to run your tests, e.g., linting
        echo "Running tests..."
        # Example: flake8 for Python linting
        # pip install flake8
        # flake8 .

    - name: Analyze code with GPT-4
      run: |
        curl -X POST http://localhost:5000/api/query -H "Content-Type: application/json" -d '{"prompt": "Analyze the following code: <your_code_here>"}'
