name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask requests python-dotenv

    - name: Run tests
      run: |
        echo "Running tests..."
        # You can add more specific test commands here if needed
        echo "Tests completed."

    - name: Debug information
      run: |
        echo "Debugging information:"
        echo "PWD: $(pwd)"
        echo "Files in current directory:"
        ls -la

    - name: Analyze code with GPT-4
      run: |
        echo "Running code analysis..."
        curl -X POST http://localhost:5000/api/query -H "Content-Type: application/json" -d '{"prompt": "Analyze the following code: <your_code_here>"}'
